// Generated by Wrangler by running `wrangler types`

interface Env {
	kv: KVNamespace;
	PSA1_APP_KEY: string;
	PSA1_APP_SECRET: string;
	PSA1_CANO: string;
	PSA2_APP_KEY: string;
	PSA2_APP_SECRET: string;
	PSA2_CANO: string;
	NOTION_API_KEY: string;
	NOTION_TOTAL_PAGE_ID: string;
	REITS_CODE: string;
	REITS_QUANTITY: string;
	NOTION_ISA_PAGE_ID: string;
	NOTION_IRP_PAGE_ID: string;
	NOTION_USD_PAGE_ID: string;
}
