#:schema node_modules/wrangler/config-schema.json
name = "asset-management-worker"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# [vars]
# MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "kv"
id = "343f035481b8467ba40c9b84ba8fff6c"
preview_id = "343f035481b8467ba40c9b84ba8fff6c"

[triggers]
crons = [
    "*/5 * * * *",
    "1,6,11,16,21,26,31,36,41,46,51,56 0-6 * * 2-6",
    "1,6,11,16,21,26,31,36,41,46,51,56 13-20 * * 2-6"
]
